### ISSUE TITLE
I just get a blank page :(

### ISSUE THREAD

**Issue by rocarvaj** [adlr/croshwindow#2]
Hello,
I really wasn't aware of how useful is this application... Until it stopped working a while ago. When opened, a blank window appears, no crosh. From what I see on the app page in the Chrome store, a lot of people is experiencing the same problem.
Thanks in advance for looking into this issue since without this app my crouton installation is not very convenient to use anymore (no Ctrl+W in Vim :( ).

Rodolfo

**Comment by MatrixManAtYrService** [comment]
Not sure if this makes sense, but today I had this problem.  Checked to see if I had secure shell installed.  I did.  Rebooted chromebook, same problem.  Then, just for grins, I opened the secure shell app and closed it.  After that, crosh was working.  Might be worth trying if you end up here.
